Add nodejs and Npgsql tests
Other runners are currently excluded.

WORKS AS EXPECTED
C# - Npgsql
Works in both master and the fix branch. Apparently Npgsql rewrites the query so it has no gaps! Wow!

Node.js
Fails on master, works on the fix branch.

psycopg2
Client-side failure: not all arguments converted during string formatting

psycopg3
Client-side failure: the query has 2 placeholders but 4 parameters were passed

PHP
Client-side failure: Invalid parameter number: parameter was not defined

TO BE INVESTIGATED
1. asyncpg
Error: Test 'Bindvar gaps with subqueries' failed: unknown function name: set_config(STRING,STRING,BOOLEAN)
Educated guess: asyncpg tries to disable JIT via set_config() when it encounter something unusual in the query. This is not supported by QuestDB.

2. Rust
error: Test 'Bindvar gaps with subqueries' failed: Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: None, code: SqlState(E00000), message: "table does not exist [table=pg_catalog.pg_range]", detail: None, hint: None, position: Some(Original(134)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: None, line: None, routine: None }) }
Something makes the Rust client to access pg_catalog.pg_range which is not supported by QuestDB. Perhaps similar to asyncpg